version: "3"
services:
  localstack:
    image: localstack/localstack:0.12.8
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis,dynamodb,cloudwatch
      - KINESIS_LATENCY=0
  aws-worker:
    image: mesosphere/aws-cli:1.14.5
    volumes:
      - "./scripts:/project/scripts"
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=eu-central-1
    entrypoint: "/project/scripts/setup.sh"